#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo -e "USAGE: weather-ma-jig place [--short]\n \
            Example: weather-ma-jig Boulder"
    exit 1
fi

# Put your app id here:
APPID="yGv9NWHV34GQ4FyA6.COP1blzCbYjHD3IzLJhlmK.b.4YpCWqv.D6LxDUodHiNyDGg--"

if [ -z $APPID ]; then
    echo "get an app id from Yahoo! Here: https://developer.apps.yahoo.com/wsregapp/"
    exit 1
fi

PLACE=$(echo $1 | sed 's/ /%20/')

WOEID=$(curl -s "http://where.yahooapis.com/v1/places.q(${PLACE})?appid=${APPID}" | grep -i woeid | sed 's/.*<woeid>\(.*\)<\/woeid>.*/\1/')

if [ -z $WOEID ]; then
    echo "$1 ain't no place I ever heard of…"
    exit 2
fi

DOW=$(date +%a)
TOM=$(date -v+1d +%a)
TODAY=true
WEATHER=$(curl -s "http://weather.yahooapis.com/forecastrss?u=f&w=${WOEID}")
CITY=$(echo "${WEATHER}" | grep -m 1 -i '<title>Yahoo! Weather' | sed 's/.*<title>Yahoo! Weather - \([^"]*\)<\/title>.*/\1/')
CURTEMP=$(echo "${WEATHER}" | grep -m 1 -i '<yweather:condition' | sed -e 's/.*temp="\([0-9]*\)" .*/\1ºF/')

DOWLN=$(echo "${WEATHER}" | grep -m 1 -i "<yweather:forecast day=\"${DOW}\"")

if [ -z "$DOWLN" ]; then
    DOWLN=$(echo "${WEATHER}" | grep -m 1 -i "<yweather:forecast day=\"${TOM}\"")
    TODAY=false
fi

FORECAST=$(echo "${DOWLN}" | sed -e "s/.*low=\"\(.*\)\" high=\"\(.*\)\" text=\"\([a-zA-Z ]*\)\" .*/\2ºF \1ºF \3/")

IFS=' ' read -r HIGH LOW CONDITIONS < <(echo $FORECAST)

if $TODAY; then
    DATE=$(date +"%A, %B %d %Y")
else
    DATE=$(date -v+1d +"%A, %B %d %Y")
fi

shopt -s nocasematch

if [[ -z $2 || $2 != '--short' ]]; then
    echo -e "\n$DATE\nForecast for $CITY\n===========================\nCURRENTLY: $CURTEMP\nHIGH: $HIGH\nLOW: $LOW"
    if [[ $CONDITIONS =~ "sunny" ]]; then
        if [[ $(uname -s) != 'Darwin' ]]; then
            tput setaf 3
            echo -e "☀  $CONDITIONS\n";
        else
            echo -e "🌞  $CONDITIONS\n";
        fi
    elif [[ $CONDITIONS =~ "storm" ]]; then
        if [[ $(uname -s) != 'Darwin' ]]; then
            tput setaf 4
            echo -e "☂  $CONDITIONS\n";
        else
            echo -e "☔  $CONDITIONS\n";
        fi
    elif [[ $CONDITIONS =~ "cloudy" ]]; then
        if [[ $(uname -s) != 'Darwin' ]]; then
            tput setaf 6
            echo -e "☁  $CONDITIONS\n";
        else
            echo -e "⛅  $CONDITIONS\n";
        fi
    else
        echo -e "$CONDITIONS\n";
    fi
    tput sgr0
else
    if [[ $CONDITIONS =~ "sunny" ]]; then
        if [[ $(uname -s) != 'Darwin' ]]; then
            tput setaf 3
            echo -e "☀ ";
        else
            echo -e "🌞 ";
        fi
    elif [[ $CONDITIONS =~ "storm" ]]; then
        if [[ $(uname -s) != 'Darwin' ]]; then
            tput setaf 4
            echo -e "☂ ";
        else
            echo -e "☔ ";
        fi
    elif [[ $CONDITIONS =~ "cloudy" ]]; then
        if [[ $(uname -s) != 'Darwin' ]]; then
            tput setaf 6
            echo -e "☁ ";
        else
            echo -e "⛅ ";
        fi
    else
        if [[ $(uname -s) != 'Darwin' ]]; then
            echo -e "( ͡° ͜ʖ ͡°)";
        else
            echo -e "👾 ";
        fi
    fi
fi
exit 0